# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 0

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 250

# Logger info
# NOTE: Tests are configured to suppress logging output into an in memory logger.
# If you want them in normal place, uncomment this section.
logging:
  level: debug

# Statsd metrics reporter
metrics:
  #type: log
  #host: localhost
  #port: 8125

services:
  - name: eventgate
    # a relative path or the name of an npm package, if different from name
    module: ./app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 6937
      # interface: localhost # uncomment to only listen on localhost
      # more per-service config settings

      # the location of the spec, defaults to spec.yaml if not specified
      spec: ./spec.test.yaml

      # the user agent to use when issuing requests
      user_agent: eventgate_test

      # Configure the EventGate test service similar to one that might be used
      # in production, but with a mock producer and a mock event error create function.
      eventgate_factory_module: '../test/utils/eventgate_test_factory'

      # This field in each event will be used to extract a destination 'stream' name.
      # This will equal the destination Kafka topic, unless a topic prefix
      #  is configured.  If using topic prefix, the value extracted
      # from this field will be prefixed with it and used as the Kafka topic.
      stream_field: meta.stream_name
      id_field: meta.id
      topic_prefix: 'test.'

      error_schema_uri: /error/0.0.1
      # TODO rename this to error_stream_name
      error_stream: eventgate.event-error
      # This field in each event will be used to extract a
      # (possibly relative) schema uri.
      schema_uri_field: $schema

      # If set, this URI will be prepended to any relative schema URI
      # extracted from each event's schema_field
      schema_base_uri: test/schemas/
      # If set, this will be appended to every extracted schema_uri if that schema_uri
      # does not already end with a file extension.
      # schema_file_extension: .yaml
