swagger: '2.0'
info:
  version: 0.4.0
  title: EventGate
  description: Validates and produces events
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  license:
    name: Apache2 License
    url: http://www.apache.org/licenses/LICENSE-2.0

paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      responses:
        200:
          description: Success
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
            headers:
              user-agent: '*'
              disallow: '/'
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      responses:
        200:
          description: Success
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: doc from root
          request:
            query:
              doc: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404

  # from routes/events.js
  /v1/events:
    post:
      description: Produce events
      produces:
        - application/json
      responses:
        204:
          description: Success
        207:
          description: Partial Success
          schema:
            $ref: '#/definitions/problem'
        400:
          description: Failure
          schema:
            $ref: '#/definitions/problem'
