swagger: '2.0'
info:
  version: 0.4.0
  title: EventGate
  description: Validates and produces events
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  license:
    name: Apache2 License
    url: http://www.apache.org/licenses/LICENSE-2.0

paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      responses:
        200:
          description: Success
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
            headers:
              user-agent: '*'
              disallow: '/'
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      responses:
        200:
          description: Success
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: doc from root
          request:
            query:
              doc: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404

  # from routes/events.js
  /v1/events:
    post:
      description: Produce events
      produces:
        - application/json
      responses:
        204:
          description: Success
        207:
          description: Partial Success
          schema:
            $ref: '#/definitions/problem'
        400:
          description: Failure
          schema:
            $ref: '#/definitions/problem'

      x-amples:
        - title: Produce a single valid event
          request:
            headers:
              content-type: application/json            
            body:
              $schema: test/0.0.1
              meta:
                stream_name: test.event
                id: "5e1dd101-641c-11e8-ab6c-b083fecf1287"
              test: test_value
          response:
            status: 204

        - title: Produce a single invalid event
          request:
            headers:
              content-type: application/json
            body:
              $schema: /test/0.0.1
              meta:
                stream_name: test.event
                id: "5e1dd101-641c-11e8-ab6c-b083fecf1287"
              test: 0.01
          response:
            status: 400
            body:
              invalid:
                - status: invalid
                  event:
                    $schema: /error/0.0.1
                    meta:
                      stream_name: eventgate.event-error
                      id: ea262403-f707-11e8-a892-c2baac54c6bc
                      dt: 2018-12-03T14:30:00.000Z

        - title: Produce a single event that encounters an error that should not be produced as an event error
          request:
            headers:
              content-type: application/json
            body:
              $schema: /test/0.0.1
              meta:
                stream_name: __throw_unproduceable_error__
                id: "5e1dd101-641c-11e8-ab6c-b083fecf1287"
              test: test_value
          response:
            status: 500

        - title: Produce a single event that encounters an error that should be produced as an event error
          request:
            headers:
              content-type: application/json
            body:
              $schema: /test/0.0.1
              meta:
                stream_name: __throw_produceable_error__
                id: "5e1dd101-641c-11e8-ab6c-b083fecf1287"
              test: test_value
          response:
            status: 500

        - title: Produce a single event that encounters an EventSchemaLoadError
          request:
            headers:
              content-type: application/json
            body:
              $schema: bad uri right here@@@
              meta:
                stream_name: test.event
                id: "5e1dd101-641c-11e8-ab6c-b083fecf1287"
              test: test_value
          response:
            status: 500
        # TODO: add response body testing on errors too.

        - title: Produce a batch valid events
          request:
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: test_value0
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
          response:
            status: 204

        - title: Produce batch events, one valid, one invalid
          request:
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: 12345
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
          response:
            status: 207

        - title: Produce batch events, one valid, one invalid, one error
          request:
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: 12345
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
              - $schema: /test/0.0.1
                meta:
                  stream_name: __throw_unproduceable_error__
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
          response:
            status: 207

        - title: Produce batch events, all invalid
          request:
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: 12345
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
                test_default: 67890
          response:
            status: 400

        - title: Produce batch events, all errored
          request:
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: __throw_unproduceable_error__
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: test_value
              - $schema: /test/0.0.1
                meta:
                  stream_name: __throw_unproduceable_error__
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
                test_default: test_value
          response:
            status: 500

        - title: Produce batch events, all invalid, fire and forget
          request:
            query:
              hasty: true
            headers:
              content-type: application/json
            body:
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1280"
                test: 12345
              - $schema: /test/0.0.1
                meta:
                  stream_name: test.event
                  id: "5e1dd101-641c-11e8-ab6c-b083fecf1281"
                test: test_value1
                test_default: 67890
          response:
            status: 204
